# Generated by Django 2.1.2 on 2018-10-12 17:27

import Medical_Donation.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('address', models.CharField(max_length=128)),
                ('pinCode', models.IntegerField(max_length=6)),
                ('Phone_no', models.IntegerField(max_length=10)),
                ('BirthDate', models.DateField()),
                ('UID', models.IntegerField(max_length=12, unique=True)),
                ('email', models.EmailField(max_length=64)),
                ('username', models.CharField(max_length=16, unique=True)),
                ('password', models.CharField(max_length=16)),
                ('image', models.ImageField(blank=True, null=True, upload_to=Medical_Donation.models.Collector.get_image_path)),
            ],
        ),
        migrations.CreateModel(
            name='Doner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('address', models.CharField(max_length=128)),
                ('pinCode', models.IntegerField(max_length=6)),
                ('Phone_no', models.IntegerField(max_length=10)),
                ('BirthDate', models.DateField()),
                ('UID', models.IntegerField(max_length=12, unique=True)),
                ('email', models.EmailField(max_length=64)),
                ('username', models.CharField(max_length=16, unique=True)),
                ('password', models.CharField(max_length=16)),
                ('image', models.ImageField(blank=True, null=True, upload_to=Medical_Donation.models.Doner.get_image_path)),
            ],
        ),
    ]
