# Generated by Django 2.1.2 on 2018-10-14 09:16

import Medical_Donation.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Medical_Donation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medical',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('proprietor', models.CharField(max_length=64)),
                ('license_no', models.CharField(max_length=64)),
                ('address', models.CharField(max_length=128)),
                ('pincode', models.PositiveIntegerField(max_length=6)),
                ('email', models.EmailField(max_length=254)),
                ('username', models.CharField(max_length=64, unique=True)),
                ('password', models.CharField(max_length=16)),
                ('Phone_no', models.IntegerField(max_length=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to=Medical_Donation.models.Collector.Medical.get_image_path)),
            ],
        ),
        migrations.AlterField(
            model_name='collector',
            name='Phone_no',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='collector',
            name='UID',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='collector',
            name='pinCode',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='doner',
            name='Phone_no',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='doner',
            name='UID',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='doner',
            name='pinCode',
            field=models.IntegerField(),
        ),
    ]
